qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY}"
  use_grpc: true

embedding:
  primary:
    provider: "gemini"
    model: "gemini-embedding-001"
    api_key: "${GEMINI_API_KEY}"
    dimensions: 768

# Issue Triage Agent Configuration
triage:
  enabled: true
  llm:
    provider: "gemini"
    model: "gemini-2.5-flash-lite"
    api_key: "${GEMINI_API_KEY}"
  router:
    enabled: true
  classifier:
    enabled: true
    min_confidence: 0.7
    labels:
      - name: "bug"
        keywords: ["error", "crash", "broken", "not working", "fails", "exception", "panic"]
      - name: "enhancement"
        keywords: ["feature", "add", "improve", "request", "would be nice", "support for"]
      - name: "question"
        keywords: ["how to", "help", "?", "wondering", "confused", "what is"]
      - name: "documentation"
        keywords: ["docs", "readme", "typo", "documentation", "example"]
      - name: "performance"
        keywords: ["slow", "memory", "cpu", "performance", "latency", "timeout"]
      - name: "security"
        keywords: ["vulnerability", "security", "CVE", "injection", "auth"]
  quality:
    enabled: true
    min_score: 0.5
    needs_info_label: "needs-info"
  duplicate:
    enabled: true
    auto_close_threshold: 0.95
    require_confirmation: false

defaults:
  similarity_threshold: 0.65
  max_similar_to_show: 5
  include_closed_issues: true
  closed_issue_weight: 0.9
  cross_repo_search: true
  comment_cooldown_hours: 1
  delayed_actions:
    enabled: true
    delay_hours: 24
    approve_reaction: "+1"
    cancel_reaction: "-1"
    execute_on_approve: false
    optimistic_transfers: true

repositories:
  - org: "similigh"
    repo: "nexusflow-core"
    description: "The core engine of NexusFlow. Handles server-side logic, performance, security, and internal system bugs."
    enabled: true
    transfer_rules:
      - match:
          title_contains: ["CLI", "command line", "nexus deploy", "nexus login", "nexus apply", "terminal"]
        target: "similigh/nexusflow-cli"
        priority: 1
      - match:
          body_contains: ["nexus deploy", "nexus login", "nexus apply", "CLI command", "command hangs", "shell completion"]
        target: "similigh/nexusflow-cli"
        priority: 2
      - match:
          title_contains: ["documentation", "docs", "tutorial", "guide", "how to"]
        target: "similigh/nexusflow-docs"
        priority: 3
      - match:
          body_contains: ["documentation", "missing docs", "need guide", "how do I"]
        target: "similigh/nexusflow-docs"
        priority: 4
      - match:
          title_contains: ["VS Code", "VSCode", "extension", "IntelliSense"]
        target: "similigh/nexusflow-vscode"
        priority: 5
      - match:
          title_contains: ["SDK", "Python SDK", "Go SDK", "TypeScript SDK", "client library"]
        target: "similigh/nexusflow-sdk"
        priority: 6
      - match:
          body_contains: ["import nexusflow", "from nexusflow", "nexusflow.NewClient"]
        target: "similigh/nexusflow-sdk"
        priority: 7

rate_limits:
  github_requests_per_second: 10
  embedding_requests_per_second: 5
  qdrant_requests_per_second: 50

# Pipeline Configuration (Execution Order)
pipeline:
  steps:
    - "gatekeeper"
    - "vectordb_prep"
    - "similarity_search"
    - "transfer_check"
    - "triage"
    - "response_builder"
    - "action_executor"
    - "indexer"
