qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY}"
  use_grpc: true

embedding:
  primary:
    provider: "gemini"
    model: "gemini-embedding-001"
    api_key: "${GEMINI_API_KEY}"
    dimensions: 768

defaults:
  similarity_threshold: 0.65
  max_similar_to_show: 5
  include_closed_issues: true
  closed_issue_weight: 0.9
  cross_repo_search: true
  comment_cooldown_hours: 1

repositories:
  - org: "similigh"
    repo: "nexusflow-core"
    enabled: true
    similarity_threshold: 0.65
    transfer_rules:
      # CLI-related issues should go to CLI repo
      - match:
          title_contains: ["CLI", "command line", "nexus deploy", "nexus login", "nexus apply", "terminal"]
        target: "similigh/nexusflow-cli"
        priority: 1
      - match:
          body_contains: ["nexus deploy", "nexus login", "nexus apply", "CLI command", "command hangs", "shell completion"]
        target: "similigh/nexusflow-cli"
        priority: 2

      # Documentation issues should go to docs repo
      - match:
          title_contains: ["documentation", "docs", "tutorial", "guide", "how to"]
        target: "similigh/nexusflow-docs"
        priority: 3
      - match:
          body_contains: ["documentation", "missing docs", "need guide", "how do I"]
        target: "similigh/nexusflow-docs"
        priority: 4

      # VS Code extension issues should go to vscode repo
      - match:
          title_contains: ["VS Code", "VSCode", "extension", "IntelliSense"]
        target: "similigh/nexusflow-vscode"
        priority: 5

      # SDK issues should go to SDK repo
      - match:
          title_contains: ["SDK", "Python SDK", "Go SDK", "TypeScript SDK", "client library"]
        target: "similigh/nexusflow-sdk"
        priority: 6
      - match:
          body_contains: ["import nexusflow", "from nexusflow", "nexusflow.NewClient"]
        target: "similigh/nexusflow-sdk"
        priority: 7

rate_limits:
  github_requests_per_second: 10
  embedding_requests_per_second: 5
  qdrant_requests_per_second: 50
